# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:


    liip_imagine.filter.loader.upscale_bis:
        class: %liip_imagine.filter.loader.upscale.class%
        tags:
            - { name: liip_imagine.filter.loader, loader: upscale_bis }
